<?xml version="1.0" encoding="utf-8"?><Database Name="Earthwise_Service" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Earthwise_Service.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Earthwise_ServiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="CartId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Cart_Checkout" Member="Checkouts" ThisKey="CartId" OtherKey="CartId" Type="Checkout" />
      <Association Name="User_Cart" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Product_Cart" Member="Product" ThisKey="ProdId" OtherKey="ProdId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoices" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Transaction_Invoice" Member="Transaction" ThisKey="TransactionId" OtherKey="TransactionId" Type="Transaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TransactionType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TaxAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DiscountAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShippingAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LoyaltyPointsEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Transaction_Invoice" Member="Invoices" ThisKey="TransactionId" OtherKey="TransactionId" Type="Invoice" />
      <Association Name="User_Transaction" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="User_Cart" Member="Carts" ThisKey="UserId" OtherKey="UserId" Type="Cart" />
      <Association Name="User_Transaction" Member="Transactions" ThisKey="UserId" OtherKey="UserId" Type="Transaction" />
      <Association Name="User_Contact" Member="Contacts" ThisKey="UserId" OtherKey="UserId" Type="Contact" />
      <Association Name="User_BillingAddress" Member="BillingAddresses" ThisKey="UserId" OtherKey="UserId" Type="BillingAddress" />
      <Association Name="User_BillingDetail" Member="BillingDetails" ThisKey="UserId" OtherKey="UserId" Type="BillingDetail" />
      <Association Name="User_OrderDetail" Member="OrderDetails" ThisKey="UserId" OtherKey="UserId" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Reports" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ReportType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumProductsSold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductOnHandInfo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NumRegisteredUsers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CarbonEmissionsSaved" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TopSellingProducts" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MonthlySalesTrends" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductAvailability" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProdId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProdName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProdDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProdPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ProdCategory" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProdImage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnSpecial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="ProdId" OtherKey="ProdId" Type="Cart" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ProdId" OtherKey="ProdId" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ContactId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="User_Contact" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BillingAddress" Member="BillingAddresses">
    <Type Name="BillingAddress">
      <Column Name="BillingAddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="User_BillingAddress" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BillingDetails" Member="BillingDetails">
    <Type Name="BillingDetail">
      <Column Name="BillingDetailsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CardNumber" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="CVV" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="User_BillingDetail" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Checkout" Member="Checkouts">
    <Type Name="Checkout">
      <Column Name="CheckoutId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckoutDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Checkout_OrderDetail" Member="OrderDetails" ThisKey="CheckoutId" OtherKey="CheckoutId" Type="OrderDetail" />
      <Association Name="Cart_Checkout" Member="Cart" ThisKey="CartId" OtherKey="CartId" Type="Cart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrderDetailsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CheckoutId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Checkout_OrderDetail" Member="Checkout" ThisKey="CheckoutId" OtherKey="CheckoutId" Type="Checkout" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProdId" OtherKey="ProdId" Type="Product" IsForeignKey="true" />
      <Association Name="User_OrderDetail" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>